# Generated by Django 5.2.7 on 2025-10-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_filestorage_alter_dumptask_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filestorage',
            options={'verbose_name': 'Хранилище', 'verbose_name_plural': 'Хранилища'},
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='db_type',
            field=models.IntegerField(choices=[(1, 'Postgres'), (2, 'ClickHouse'), (3, 'Mysql')], verbose_name='Тип'),
        ),
    ]
