# Generated by Django 6.0.1 on 2026-01-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_filestorage_options_alter_userdatabase_db_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dumptask',
            options={'verbose_name': 'Dump Task', 'verbose_name_plural': 'Dump Tasks'},
        ),
        migrations.AlterModelOptions(
            name='dumptaskoperation',
            options={'verbose_name': 'Dump Task Operation', 'verbose_name_plural': 'Dump Tasks Operations'},
        ),
        migrations.AlterModelOptions(
            name='filestorage',
            options={'verbose_name': 'File storage', 'verbose_name_plural': 'File storages'},
        ),
        migrations.AlterModelOptions(
            name='recoverbackupoperation',
            options={'verbose_name': 'Recover Backup Operation', 'verbose_name_plural': 'Recover Backup Operations'},
        ),
        migrations.AlterModelOptions(
            name='userdatabase',
            options={'verbose_name': 'Database', 'verbose_name_plural': 'Databases'},
        ),
        migrations.AlterField(
            model_name='dumptask',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='dumptask',
            name='max_dumpfiles_keep',
            field=models.PositiveIntegerField(default=1, verbose_name='Max Dump files count to keep'),
        ),
        migrations.AlterField(
            model_name='dumptask',
            name='task_period',
            field=models.IntegerField(choices=[(1, 'Never'), (2, 'Every day'), (3, 'Every week'), (4, 'Every month')], verbose_name='Task Period'),
        ),
        migrations.AlterField(
            model_name='dumptask',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of update'),
        ),
        migrations.AlterField(
            model_name='dumptaskoperation',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='dumptaskoperation',
            name='dump_path',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Dump File Path'),
        ),
        migrations.AlterField(
            model_name='dumptaskoperation',
            name='error_text',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Error text'),
        ),
        migrations.AlterField(
            model_name='dumptaskoperation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'In Process'), (3, 'Fail'), (4, 'Success')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='dumptaskoperation',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of update'),
        ),
        migrations.AlterField(
            model_name='filestorage',
            name='host',
            field=models.CharField(blank=True, help_text='S3 endpoint (для S3). Для Yandex Disk можно оставить пустым', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recoverbackupoperation',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='recoverbackupoperation',
            name='error_text',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Error text'),
        ),
        migrations.AlterField(
            model_name='recoverbackupoperation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'In Process'), (3, 'Fail'), (4, 'Success')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='recoverbackupoperation',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of update'),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='connection_string',
            field=models.TextField(verbose_name='Connection Link'),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='db_type',
            field=models.IntegerField(choices=[(1, 'Postgres'), (2, 'ClickHouse'), (3, 'Mysql')], verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of update'),
        ),
    ]
