# Generated by Django 5.2.10 on 2026-01-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_dumptask_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestorage',
            name='access_key',
            field=models.CharField(blank=True, help_text='S3 Access Key / FTP/SFTP username', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filestorage',
            name='bucket_name',
            field=models.CharField(blank=True, help_text='S3 bucket (для S3). FTP/SFTP базовый путь', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filestorage',
            name='host',
            field=models.CharField(blank=True, help_text='S3 endpoint / FTP/SFTP host. Для Yandex Disk можно оставить пустым', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filestorage',
            name='secret_key',
            field=models.CharField(blank=True, help_text='S3 Secret Key / OAuth-токен (Yandex Disk) / FTP/SFTP password', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filestorage',
            name='type',
            field=models.CharField(choices=[('s3', 'S3'), ('yadisk', 'Yandex Disk'), ('ftp', 'FTP'), ('sftp', 'SFTP')], default='s3', max_length=10),
        ),
    ]
