#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Запуск cron в фоновом режиме
cron

python manage.py collectstatic --noinput
python manage.py migrate
python manage.py init_admin
exec gunicorn config.wsgi:application --bind 0.0.0.0:8009 --reload --workers 4
